#!/bin/sh
#  prints a string describing the installed distribution if possible
#
#  Exit Code: 0 if description found else 4
#
export LANG=C

desc=

set +f

for release_file in /etc/?*-release; do
   [ -f "${release_file}" ] && [ -r "${release_file}" ] || continue

   fname="${release_file##*/}"; fname="${fname%-release}"

   case "${fname}" in
      os)
         unset -v PRETTY_NAME NAME ID VERSION

         if ! { . "${release_file}" --; } 1>/dev/null 2>/dev/null; then
            # %desc could have been modified by %release_file, reset it
            #  (overwrites any previous lsb-release %desc)
            desc=

         elif [ -n "${PRETTY_NAME-}" ]; then
            desc="${PRETTY_NAME}"

         elif [ -n "${NAME-}" ]; then
            desc="${NAME}${VERSION:+ ${VERSION}}"
         fi

         # no break
      ;;

      lsb)
         unset -v \
            LSB_VERSION \
            DISTRIB_ID DISTRIB_RELEASE DISTRIB_CODENAME DISTRIB_DESCRIPTION

         if ! { . "${release_file}" --; } 1>/dev/null 2>/dev/null; then
            desc=

         elif [ -n "${DISTRIB_DESCRIPTION-}" ]; then
            desc="${DISTRIB_DESCRIPTION}"

         elif [ -n "${DISTRIB_ID-}" ]; then
            desc="\
${DISTRIB_ID}\
${DISTRIB_RELEASE:+ release ${DISTRIB_RELEASE}}\
${DISTRIB_CODENAME:+ (${DISTRIB_CODENAME})}"
         fi

         # no break
      ;;

      *)
         # [distrib]-release file, read && break loop
         desc=
         if \
            { read -r desc < "${release_file}"; } 2>/dev/null && \
            [ -n "${desc}" ]
         then
            # inline script-end commands, no need to check "-n $desc" twice
            printf "%s\n" "${desc}"
            exit 0
            #break
         fi
      ;;
   esac
done



if [ -n "${desc-}" ]; then
   printf "%s\n" "${desc}"
   exit 0
else
   exit 4
fi
